### ISSUE TITLE
Data for outlier detection experiments

### ISSUE THREAD

**Issue by jcklie** [clinc/uniqueness#1]
Hi,
I am Jan,  a PhD student from TU Darmstadt, Germany and currently researching annotation correction. I saw your paper "Outlier Detection for Improved Data Quality and Diversity in Dialog Systems" and found it really interesting. Do you have the real and artificial data hosted somewhere or can you share it with me? Sadly, I did not find a reference to it. This would really help my research, as corpora that have a erroneous and corrected part are quite rare.
Best,

**Comment by gxlarson** [comment]
Unfortunately I don't have the real vs. artificial data from the experiments in Section 4.1 of the paper. However you might find [this paper on errors in crowdsourced paraphrases](https://www.aclweb.org/anthology/N19-1026.pdf) useful. The dataset for that paper is available online here: https://github.com/mysilver/ParaQuality

**Comment by gxlarson** [comment]
I also have a related paper on errors in slot-filling annotations: https://www.aclweb.org/anthology/2020.coling-main.442.pdf. This paper has a link to datasets.

**Comment by jcklie** [comment]
Thank you! That is very helpful.
